# Generated by Django 6.0.5 on 2026-05-14 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_businessprofile_supplier_customer_credit_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='selected_modules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('google_sheets', 'Google Sheets'), ('excel_online', 'Microsoft Excel Online'), ('whatsapp', 'WhatsApp Business'), ('offline_excel', 'Offline Excel'), ('mtn_momo', 'MTN MoMo'), ('airtel_money', 'Airtel Money')], max_length=40)),
                ('display_name', models.CharField(max_length=140)),
                ('account_identifier', models.CharField(blank=True, max_length=220)),
                ('status', models.CharField(choices=[('not_connected', 'Not Connected'), ('connected', 'Connected'), ('needs_setup', 'Needs Setup')], default='needs_setup', max_length=30)),
                ('sync_direction', models.CharField(default='Import and export', max_length=80)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='core.businessprofile')),
            ],
            options={
                'ordering': ['connection_type'],
                'unique_together': {('profile', 'connection_type')},
            },
        ),
    ]
