# Generated by Django 6.0.5 on 2026-05-14 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_businessprofile_firebase_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.businessprofile'),
        ),
        migrations.AddField(
            model_name='branch',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.businessprofile'),
        ),
        migrations.AddField(
            model_name='category',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.businessprofile'),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.businessprofile'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.businessprofile'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('profile', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('branch', 'sku')},
        ),
    ]
