# Generated by Django 6.0.5 on 2026-05-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_activitylog_profile_branch_profile_category_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='business_type',
            field=models.CharField(choices=[('shop', 'Shop'), ('boutique', 'Boutique'), ('restaurant', 'Restaurant'), ('pharmacy', 'Pharmacy'), ('hardware', 'Hardware Store'), ('hotel', 'Hotel'), ('mini_market', 'Mini Market'), ('wholesale', 'Wholesale'), ('school', 'School'), ('club', 'Club'), ('other', 'Other Business')], default='shop', max_length=40),
        ),
    ]
