# Generated by Django 6.0.5 on 2026-05-15 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


DEFAULT_PERMISSIONS = {
    'view_dashboard': 'View dashboard',
    'view_reports': 'View reports',
    'create_sale': 'Create sale',
    'edit_inventory': 'Edit inventory',
    'manage_staff': 'Manage staff',
}

DEFAULT_ROLES = {
    'admin': {
        'display_name': 'Admin',
        'permissions': list(DEFAULT_PERMISSIONS),
    },
    'manager': {
        'display_name': 'Manager',
        'permissions': ['view_dashboard', 'view_reports', 'create_sale', 'edit_inventory', 'manage_staff'],
    },
    'cashier': {
        'display_name': 'Cashier',
        'permissions': ['view_dashboard', 'create_sale'],
    },
    'stock_controller': {
        'display_name': 'Stock Controller',
        'permissions': ['view_dashboard', 'edit_inventory'],
    },
    'accountant': {
        'display_name': 'Accountant',
        'permissions': ['view_dashboard', 'view_reports'],
    },
    'waiter': {
        'display_name': 'Waiter',
        'permissions': ['view_dashboard', 'create_sale'],
    },
    'receptionist': {
        'display_name': 'Receptionist',
        'permissions': ['view_dashboard', 'create_sale'],
    },
    'staff': {
        'display_name': 'Staff',
        'permissions': ['view_dashboard'],
    },
}


def seed_default_roles_and_permissions(apps, schema_editor):
    Permission = apps.get_model('core', 'Permission')
    Role = apps.get_model('core', 'Role')
    RolePermission = apps.get_model('core', 'RolePermission')

    permissions = {}
    for code, name in DEFAULT_PERMISSIONS.items():
        permissions[code], _ = Permission.objects.get_or_create(code=code, defaults={'name': name})

    for role_name, role_config in DEFAULT_ROLES.items():
        role, _ = Role.objects.get_or_create(
            name=role_name,
            defaults={'display_name': role_config['display_name']},
        )
        for permission_code in role_config['permissions']:
            RolePermission.objects.get_or_create(role=role, permission=permissions[permission_code])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_businessprofile_business_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.role')),
            ],
            options={
                'ordering': ['role__name', 'permission__code'],
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='UserBusinessAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(blank=True, max_length=140)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='core.businessprofile')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_accesses', to='core.role')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['business__name', 'role__name'],
                'unique_together': {('user', 'business')},
            },
        ),
        migrations.RunPython(seed_default_roles_and_permissions, migrations.RunPython.noop),
    ]
