# Generated by Django 6.0.5 on 2026-05-15 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_permission_role_rolepermission_userbusinessaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('product', 'Product'), ('service', 'Service')], default='product', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='track_inventory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers', to='core.product'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_type',
            field=models.CharField(choices=[('shop', 'Shop'), ('boutique', 'Boutique'), ('restaurant', 'Restaurant'), ('pharmacy', 'Pharmacy'), ('hardware', 'Hardware Store'), ('hotel', 'Hotel'), ('mini_market', 'Mini Market'), ('wholesale', 'Wholesale'), ('salon', 'Salon / Barber Shop'), ('clinic', 'Clinic / Health Service'), ('garage', 'Garage / Auto Repair'), ('laundry', 'Laundry / Dry Cleaning'), ('construction', 'Construction / Field Service'), ('agency', 'Professional Service Agency'), ('school', 'School'), ('club', 'Club'), ('other', 'Other Business')], default='shop', max_length=40),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('stock_in', 'Stock In'), ('stock_out', 'Stock Out'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('sale', 'Sale'), ('adjustment', 'Adjustment')], max_length=30)),
                ('quantity', models.IntegerField()),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='core.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
