# Generated by Django 6.0.5 on 2026-05-15 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_item_type_product_track_inventory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='firebase_uid',
        ),
        migrations.RemoveField(
            model_name='userbusinessaccess',
            name='firebase_uid',
        ),
    ]
