# Generated by ChatGPT on 2026-05-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_passwordresetcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField('businessprofile', 'plan', models.CharField(default='free_trial', max_length=30)),
        migrations.AddField('businessprofile', 'trial_started_at', models.DateTimeField(blank=True, null=True)),
        migrations.AddField('businessprofile', 'trial_ends_at', models.DateTimeField(blank=True, null=True)),
        migrations.AddField('businessprofile', 'subscription_status', models.CharField(default='trial', max_length=30)),
        migrations.AddField('businessprofile', 'max_branches', models.PositiveIntegerField(default=1)),
        migrations.AddField('businessprofile', 'max_employees', models.PositiveIntegerField(default=5)),
        migrations.AddField('businessprofile', 'max_products', models.PositiveIntegerField(default=200)),
        migrations.AddField('sale', 'discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
        migrations.AddField('sale', 'amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
        migrations.AddField('sale', 'balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
    ]
