# Generated by Django 6.0.5 on 2026-05-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_business_trial_email_verification_partial_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('stock_in', 'Stock In'), ('stock_out', 'Stock Out'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('sale', 'Sale'), ('damaged', 'Damaged Stock'), ('expired', 'Expired Stock'), ('adjustment', 'Adjustment')], max_length=30),
        ),
    ]
