from django.urls import path

from . import views

urlpatterns = [
    path('health/', views.health_check, name='health_check'),
    path('tour/', views.tour, name='tour'),
    path('auth/', views.auth_view, name='auth'),
    path('auth/register/', views.register_view, name='register'),
    path('verify-email/', views.verify_email, name='verify_email'),
    path('auth/password-reset/', views.password_reset_request, name='password_reset'),
    path('auth/password-reset/verify/', views.password_reset_verify, name='password_reset_verify'),
    path('auth/reset/complete/', views.password_reset_complete, name='password_reset_complete'),
    path('logout/', views.logout_view, name='logout'),
    path('workspace/', views.workspace, name='workspace'),
    path('workspace/new/', views.start_new_business, name='start_new_business'),
    path('workspace/<int:pk>/open/', views.open_business, name='open_business'),
    path('onboarding/', views.onboarding, name='onboarding'),
    path('', views.dashboard, name='dashboard'),
    path('pos/', views.pos, name='pos'),
    path('sales/<int:pk>/', views.sale_detail, name='sale_detail'),
    path('inventory/', views.inventory, name='inventory'),
    path('customers/', views.customers, name='customers'),
    path('employees/', views.employees, name='employees'),
    path('hospitality/', views.hospitality, name='hospitality'),
    path('reports/', views.reports, name='reports'),
    path('notifications/', views.notifications, name='notifications'),
    path('purchases/', views.purchases, name='purchases'),
    path('daily-close/', views.daily_close, name='daily_close'),
    path('backup-center/', views.backup_center, name='backup_center'),
    path('integrations/', views.integrations, name='integrations'),
    path('integrations/<slug:connection_type>/', views.connect_integration, name='connect_integration'),
    path('integrations/<slug:connection_type>/sync/', views.sync_integration, name='sync_integration'),
    path('import-excel/', views.import_excel, name='import_excel'),
    path('export-excel/', views.export_excel, name='export_excel'),
    path('payments/', views.payments, name='payments'),
    path('team/', views.team, name='team'),
    path('expenses/', views.expenses, name='expenses'),
    path('transfers/', views.transfers, name='transfers'),
    path('stock-movements/', views.stock_movements, name='stock_movements'),
    path('manage/<slug:resource>/', views.crud_list, name='crud_list'),
    path('manage/<slug:resource>/add/', views.crud_create, name='crud_create'),
    path('manage/<slug:resource>/<int:pk>/edit/', views.crud_update, name='crud_update'),
    path('manage/<slug:resource>/<int:pk>/delete/', views.crud_delete, name='crud_delete'),
]
